/**
 * Contentful GraphQL Extension Error Codes
 * @see https://www.contentful.com/developers/docs/references/graphql/#/reference/graphql-errors
 */

export const ContentfulGraphQLExtensionCode = {
  ACCESS_TOKEN_MISSING: 'ACCESS_TOKEN_MISSING',
  ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
  COLLIDING_TYPE_NAMES: 'COLLIDING_TYPE_NAMES',
  COLLIDING_FIELD_NAMES: 'COLLIDING_FIELD_NAMES',
  RESERVED_FIELD_NAME: 'RESERVED_FIELD_NAME',
  UNKNOWN_ENVIRONMENT: 'UNKNOWN_ENVIRONMENT',
  UNKNOWN_SPACE: 'UNKNOWN_SPACE',
  MISSING_QUERY: 'MISSING_QUERY',
  QUERY_TOO_BIG: 'QUERY_TOO_BIG',
  INVALID_QUERY_FORMAT: 'INVALID_QUERY_FORMAT',
  PERSISTED_QUERY_NOT_FOUND: 'PersistedQueryNotFound',
  PERSISTED_QUERY_MISMATCH: 'PersistedQueryMismatch',
  INVALID_VARIABLES_FORMAT: 'INVALID_VARIABLES_FORMAT',
  TOO_COMPLEX_QUERY: 'TOO_COMPLEX_QUERY',
  QUERY_OPERATION_NAME_MISMATCH: 'QUERY_OPERATION_NAME_MISMATCH',
  UNKNOWN_LOCALE: 'UNKNOWN_LOCALE',
  UNRESOLVABLE_LINK: 'UNRESOLVABLE_LINK',
  UNEXPECTED_LINKED_CONTENT_TYPE: 'UNEXPECTED_LINKED_CONTENT_TYPE',
  UNRESOLVABLE_RESOURCE_LINK: 'UNRESOLVABLE_RESOURCE_LINK',
  RESOURCES_EXHAUSTED: 'RESOURCES_EXHAUSTED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type ContentfulGraphQLExtensionCodeType =
  (typeof ContentfulGraphQLExtensionCode)[keyof typeof ContentfulGraphQLExtensionCode];
